#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openjdk10
Version  : 10.0.2+13
Release  : 1
URL      : http://hg.openjdk.java.net/jdk-updates/jdk10u/archive/jdk-10.0.2+13.tar.bz2
Source0  : http://hg.openjdk.java.net/jdk-updates/jdk10u/archive/jdk-10.0.2+13.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 Libpng MIT
Requires: openjdk10-lib = %{version}-%{release}
Requires: openjdk10-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : ca-certs
BuildRequires : ccache
BuildRequires : cups-dev
BuildRequires : fontconfig-dev
BuildRequires : freetype-dev
BuildRequires : glibc-bin
BuildRequires : graphviz
BuildRequires : libX11-dev
BuildRequires : libXext-dev
BuildRequires : libXi-dev
BuildRequires : libXrender-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : openjdk9
BuildRequires : openjdk9-dev
BuildRequires : zip

%description
Welcome to OpenJDK!
===================
For information about building OpenJDK, including how to fully retrieve all
source code, please see either of these:

%package dev
Summary: dev components for the openjdk10 package.
Group: Development
Requires: openjdk10-lib = %{version}-%{release}
Provides: openjdk10-devel = %{version}-%{release}

%description dev
dev components for the openjdk10 package.


%package lib
Summary: lib components for the openjdk10 package.
Group: Libraries
Requires: openjdk10-license = %{version}-%{release}

%description lib
lib components for the openjdk10 package.


%package license
Summary: license components for the openjdk10 package.
Group: Default

%description license
license components for the openjdk10 package.


%prep
%setup -q -n jdk10u-jdk-10.0.2+13

%build
## build_prepend content
CLR_TRUST_STORE=%{_builddir}/trust-store clrtrust generate
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
export CXXFLAGS="$CXXFLAGS -std=gnu++98 -Wno-error -fno-delete-null-pointer-checks -fno-guess-branch-probability"
export CXXFLAGS_JDK="$CXXFLAGS"
export SYSDEFS="$CXXFLAGS"
bash configure \
--with-boot-jdk=/usr/lib/jvm/java-1.9.0-openjdk \
--x-includes=/usr/include/ \
--x-libraries=/usr/lib64 \
--with-extra-cflags="-O3 -g1" \
--with-extra-cxxflags="$CXXFLAGS -g1" \
--with-zlib=system \
--enable-unlimited-crypto \
--with-cacerts-file=%{_builddir}/trust-store/compat/ca-roots.keystore \
--enable-ccache \
--disable-warnings-as-errors \
--prefix=%{buildroot}/usr/lib
pushd build/linux-x86_64-normal-server-release/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548112118
make images WARNINGS_ARE_ERRORS="-Wno-error" CFLAGS_WARNINGS_ARE_ERRORS="-Wno-error"


%install
export SOURCE_DATE_EPOCH=1548112118
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openjdk10
cp LICENSE %{buildroot}/usr/share/package-licenses/openjdk10/LICENSE
cp src/java.desktop/share/native/libsplashscreen/giflib/COPYING %{buildroot}/usr/share/package-licenses/openjdk10/src_java.desktop_share_native_libsplashscreen_giflib_COPYING
cp src/java.desktop/share/native/libsplashscreen/libpng/LICENSE %{buildroot}/usr/share/package-licenses/openjdk10/src_java.desktop_share_native_libsplashscreen_libpng_LICENSE
cp src/java.smartcardio/unix/native/libj2pcsc/MUSCLE/COPYING %{buildroot}/usr/share/package-licenses/openjdk10/src_java.smartcardio_unix_native_libj2pcsc_MUSCLE_COPYING
cp test/fmw/gtest/LICENSE %{buildroot}/usr/share/package-licenses/openjdk10/test_fmw_gtest_LICENSE
cp test/jdk/javax/xml/ws/xsanymixed/CopyingResponse.java %{buildroot}/usr/share/package-licenses/openjdk10/test_jdk_javax_xml_ws_xsanymixed_CopyingResponse.java
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/bin/appletviewer
/usr/lib/bin/idlj
/usr/lib/bin/jaotc
/usr/lib/bin/jar
/usr/lib/bin/jarsigner
/usr/lib/bin/java
/usr/lib/bin/javac
/usr/lib/bin/javadoc
/usr/lib/bin/javap
/usr/lib/bin/jcmd
/usr/lib/bin/jconsole
/usr/lib/bin/jdb
/usr/lib/bin/jdeprscan
/usr/lib/bin/jdeps
/usr/lib/bin/jhsdb
/usr/lib/bin/jimage
/usr/lib/bin/jinfo
/usr/lib/bin/jjs
/usr/lib/bin/jlink
/usr/lib/bin/jmap
/usr/lib/bin/jmod
/usr/lib/bin/jps
/usr/lib/bin/jrunscript
/usr/lib/bin/jshell
/usr/lib/bin/jstack
/usr/lib/bin/jstat
/usr/lib/bin/jstatd
/usr/lib/bin/keytool
/usr/lib/bin/orbd
/usr/lib/bin/pack200
/usr/lib/bin/rmic
/usr/lib/bin/rmid
/usr/lib/bin/rmiregistry
/usr/lib/bin/schemagen
/usr/lib/bin/serialver
/usr/lib/bin/servertool
/usr/lib/bin/tnameserv
/usr/lib/bin/unpack200
/usr/lib/bin/wsgen
/usr/lib/bin/wsimport
/usr/lib/bin/xjc
/usr/lib/jvm/openjdk-10.0.2-internal/bin/appletviewer
/usr/lib/jvm/openjdk-10.0.2-internal/bin/idlj
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jaotc
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jar
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jarsigner
/usr/lib/jvm/openjdk-10.0.2-internal/bin/java
/usr/lib/jvm/openjdk-10.0.2-internal/bin/javac
/usr/lib/jvm/openjdk-10.0.2-internal/bin/javadoc
/usr/lib/jvm/openjdk-10.0.2-internal/bin/javap
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jcmd
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jconsole
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jdb
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jdeprscan
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jdeps
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jhsdb
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jimage
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jinfo
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jjs
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jlink
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jmap
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jmod
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jps
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jrunscript
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jshell
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jstack
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jstat
/usr/lib/jvm/openjdk-10.0.2-internal/bin/jstatd
/usr/lib/jvm/openjdk-10.0.2-internal/bin/keytool
/usr/lib/jvm/openjdk-10.0.2-internal/bin/orbd
/usr/lib/jvm/openjdk-10.0.2-internal/bin/pack200
/usr/lib/jvm/openjdk-10.0.2-internal/bin/rmic
/usr/lib/jvm/openjdk-10.0.2-internal/bin/rmid
/usr/lib/jvm/openjdk-10.0.2-internal/bin/rmiregistry
/usr/lib/jvm/openjdk-10.0.2-internal/bin/schemagen
/usr/lib/jvm/openjdk-10.0.2-internal/bin/serialver
/usr/lib/jvm/openjdk-10.0.2-internal/bin/servertool
/usr/lib/jvm/openjdk-10.0.2-internal/bin/tnameserv
/usr/lib/jvm/openjdk-10.0.2-internal/bin/unpack200
/usr/lib/jvm/openjdk-10.0.2-internal/bin/wsgen
/usr/lib/jvm/openjdk-10.0.2-internal/bin/wsimport
/usr/lib/jvm/openjdk-10.0.2-internal/bin/xjc
/usr/lib/jvm/openjdk-10.0.2-internal/conf/logging.properties
/usr/lib/jvm/openjdk-10.0.2-internal/conf/management/jmxremote.access
/usr/lib/jvm/openjdk-10.0.2-internal/conf/management/jmxremote.password.template
/usr/lib/jvm/openjdk-10.0.2-internal/conf/management/management.properties
/usr/lib/jvm/openjdk-10.0.2-internal/conf/net.properties
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/java.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/java.security
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/limited/default_US_export.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/limited/default_local.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/limited/exempt_local.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/unlimited/default_US_export.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/security/policy/unlimited/default_local.policy
/usr/lib/jvm/openjdk-10.0.2-internal/conf/sound.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/README
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/ArcCanvas.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/ArcControls.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/ArcTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/ArcTest.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/IntegerTextField.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/ArcTest/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/BarChart/BarChart.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/BarChart/BarChart.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/BarChart/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/BarChart/example2.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Blink/Blink$1.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Blink/Blink.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Blink/Blink.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Blink/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/CardTest/CardPanel.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/CardTest/CardTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/CardTest/CardTest.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/CardTest/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Clock/Clock.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Clock/Clock.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Clock/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/CardinalTextField.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherCanvas.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherControls.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherMethod.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherTest$1.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/DitherTest.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DitherTest/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DrawTest/DrawControls.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DrawTest/DrawPanel.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DrawTest/DrawTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DrawTest/DrawTest.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/DrawTest/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/CLSFractal.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/CLSFractal.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/CLSRule.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/CLSTurtle.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/ContextLSystem.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/Fractal/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/AppletFrame.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/AppletFrame.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/ArcCard.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/ArcDegreePanel.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/ArcPanel.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/ColorUtils.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/GraphicsCards.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/GraphicsPanel.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/GraphicsTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/GraphicsTest.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/OvalShape.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/PolygonShape.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/RectShape.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/RoundRectShape.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/Shape.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/ShapeTest.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/GraphicsTest/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/Matrix3D.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/MoleculeViewer.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/XYZApp.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/example2.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/example3.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/MoleculeViewer/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/NervousText/NervousText.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/NervousText/NervousText.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/NervousText/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SimpleGraph/GraphApplet.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SimpleGraph/GraphApplet.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SimpleGraph/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/BidirBubbleSortAlgorithm.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/BidirBubbleSortAlgorithm.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/BubbleSortAlgorithm.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/BubbleSortAlgorithm.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/QSortAlgorithm.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/QSortAlgorithm.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/SortAlgorithm.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/SortAlgorithm.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/SortItem.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/SortItem.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SortDemo/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/Cell.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/CellUpdater.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/InputField.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/Node.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/SpreadSheet.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/SpreadSheet.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/SpreadSheetInput.class
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/SpreadSheet/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/Matrix3D.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/ThreeD.java
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/WireFrame.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/example1.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/example2.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/example3.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/example4.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/applets/WireFrame/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/CodePointIM/CodePointIM.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/CodePointIM/README.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/CodePointIM/README_ja.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/CodePointIM/README_zh_CN.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/CodePointIM/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/FileChooserDemo/FileChooserDemo.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/FileChooserDemo/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/FileChooserDemo/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Font2DTest/Font2DTest.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Font2DTest/Font2DTest.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Font2DTest/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Font2DTest/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Metalworks/Metalworks.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Metalworks/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Metalworks/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Notepad/Notepad.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Notepad/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/Notepad/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SampleTree/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SampleTree/SampleTree.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SampleTree/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SwingApplet/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SwingApplet/SwingApplet.html
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SwingApplet/SwingApplet.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/SwingApplet/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TableExample/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TableExample/TableExample.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TableExample/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TransparentRuler/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TransparentRuler/TransparentRuler.jar
/usr/lib/jvm/openjdk-10.0.2-internal/demo/jfc/TransparentRuler/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/README.txt
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/FileChooserDemo/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Font2DTest/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Metalworks/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/Notepad/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SampleTree/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/SwingApplet/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TableExample/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/jfc/TransparentRuler/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/FullThreadDump/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/JTop/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/MemoryMonitor/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/management/VerboseGC/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/build.properties
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/build.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/nbproject/file-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/nbproject/jdk.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/nbproject/netbeans-targets.xml
/usr/lib/jvm/openjdk-10.0.2-internal/demo/nbproject/scripting/jconsole-plugin/nbproject/project.xml
/usr/lib/jvm/openjdk-10.0.2-internal/include/ir.idl
/usr/lib/jvm/openjdk-10.0.2-internal/include/orb.idl
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.activation.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.base.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.compiler.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.corba.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.datatransfer.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.desktop.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.instrument.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.logging.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.management.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.management.rmi.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.naming.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.prefs.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.rmi.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.scripting.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.se.ee.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.se.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.security.jgss.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.security.sasl.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.smartcardio.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.sql.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.sql.rowset.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.transaction.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.xml.bind.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.xml.crypto.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.xml.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.xml.ws.annotation.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/java.xml.ws.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.accessibility.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.aot.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.attach.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.charsets.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.compiler.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.crypto.cryptoki.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.crypto.ec.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.dynalink.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.editpad.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.hotspot.agent.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.httpserver.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.incubator.httpclient.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.ed.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.jvmstat.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.le.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.opt.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.vm.ci.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.vm.compiler.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.internal.vm.compiler.management.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jartool.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.javadoc.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jcmd.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jconsole.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jdeps.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jdi.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jdwp.agent.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jlink.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jshell.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jsobject.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.jstatd.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.localedata.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.management.agent.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.management.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.naming.dns.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.naming.rmi.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.net.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.pack.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.rmic.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.scripting.nashorn.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.scripting.nashorn.shell.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.sctp.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.security.auth.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.security.jgss.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.unsupported.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.xml.bind.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.xml.dom.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.xml.ws.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/jmods/jdk.zipfs.jmod
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.activation/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.activation/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.activation/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/aes.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/asm.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/cldr.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/icu.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.base/zlib.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.compiler/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.corba/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.corba/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.corba/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.datatransfer/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.datatransfer/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.datatransfer/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/colorimaging.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/giflib.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/harfbuzz.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/jpeg.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/lcms.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/libpng.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/mesa3d.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/opengl.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.desktop/xwindows.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.instrument/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.instrument/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.instrument/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.logging/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.logging/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.logging/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management.rmi/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.management/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.naming/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.naming/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.naming/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.prefs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.prefs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.prefs/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.rmi/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.scripting/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.scripting/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.scripting/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se.ee/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se.ee/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se.ee/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.se/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.jgss/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.sasl/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.sasl/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.security.sasl/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.smartcardio/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.smartcardio/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.smartcardio/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.smartcardio/pcsclite.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql.rowset/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql.rowset/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql.rowset/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.sql/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.transaction/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.transaction/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.transaction/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.bind/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.bind/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.bind/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.crypto/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.crypto/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.crypto/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.crypto/santuario.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws.annotation/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws.annotation/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws.annotation/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml.ws/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/bcel.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/dom.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/jcup.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/xalan.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/java.xml/xerces.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.accessibility/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.accessibility/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.accessibility/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.aot/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.aot/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.aot/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.attach/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.attach/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.attach/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.charsets/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.charsets/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.charsets/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.compiler/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.cryptoki/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.cryptoki/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.cryptoki/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.cryptoki/pkcs11cryptotoken.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.cryptoki/pkcs11wrapper.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.ec/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.ec/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.ec/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.crypto.ec/ecc.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.dynalink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.dynalink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.dynalink/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.dynalink/dynalink.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.editpad/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.editpad/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.editpad/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.hotspot.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.hotspot.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.hotspot.agent/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.httpserver/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.httpserver/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.httpserver/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.incubator.httpclient/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.incubator.httpclient/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.incubator.httpclient/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.ed/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.ed/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.ed/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.jvmstat/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.jvmstat/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.jvmstat/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.le/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.le/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.le/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.le/jline.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.opt/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.opt/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.opt/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.opt/jopt-simple.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.ci/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.ci/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.ci/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler.management/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.internal.vm.compiler/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jartool/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jartool/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jartool/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/jquery.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/jszip.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.javadoc/pako.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jcmd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jcmd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jcmd/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jconsole/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jconsole/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jconsole/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdeps/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdeps/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdeps/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdi/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdwp.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdwp.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jdwp.agent/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jlink/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jlink/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jlink/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jshell/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jshell/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jshell/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jsobject/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jsobject/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jsobject/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jstatd/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jstatd/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.jstatd/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.localedata/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.localedata/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.localedata/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.localedata/cldr.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.localedata/thaidict.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management.agent/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management.agent/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management.agent/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.management/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.dns/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.dns/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.dns/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.rmi/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.rmi/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.naming.rmi/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.net/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.net/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.net/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.pack/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.pack/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.pack/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.rmic/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.rmic/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.rmic/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn.shell/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn.shell/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn.shell/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn/double-conversion.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.scripting.nashorn/joni.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.sctp/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.sctp/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.sctp/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.auth/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.auth/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.auth/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.jgss/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.jgss/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.security.jgss/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.unsupported/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.unsupported/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.unsupported/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/freebxml.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/relaxngdatatype.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/rngom.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.bind/xmlresolver.md
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.dom/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.dom/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.dom/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.ws/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.ws/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.xml.ws/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.zipfs/ADDITIONAL_LICENSE_INFO
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.zipfs/ASSEMBLY_EXCEPTION
/usr/lib/jvm/openjdk-10.0.2-internal/legal/jdk.zipfs/LICENSE
/usr/lib/jvm/openjdk-10.0.2-internal/lib/classlist
/usr/lib/jvm/openjdk-10.0.2-internal/lib/ct.sym
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jexec
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jexec.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jli/libjli.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jrt-fs.jar
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jvm.cfg
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libattach.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt_headless.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt_xawt.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libdt_socket.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libextnet.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libinstrument.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2gss.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2pcsc.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2pkcs11.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjaas_unix.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjava.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjavajpeg.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjawt.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjdwp.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjimage.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsig.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsound.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsoundalsa.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/liblcms.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement_agent.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement_ext.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmlib_image.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libnet.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libnio.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libprefs.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/librmi.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsaproc.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsctp.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsplashscreen.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsunec.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libunpack.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libverify.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libzip.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/modules
/usr/lib/jvm/openjdk-10.0.2-internal/lib/psfont.properties.ja
/usr/lib/jvm/openjdk-10.0.2-internal/lib/psfontj2d.properties
/usr/lib/jvm/openjdk-10.0.2-internal/lib/security/blacklisted.certs
/usr/lib/jvm/openjdk-10.0.2-internal/lib/security/cacerts
/usr/lib/jvm/openjdk-10.0.2-internal/lib/security/default.policy
/usr/lib/jvm/openjdk-10.0.2-internal/lib/server/Xusage.txt
/usr/lib/jvm/openjdk-10.0.2-internal/lib/server/libjsig.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/server/libjvm.debuginfo
/usr/lib/jvm/openjdk-10.0.2-internal/lib/src.zip
/usr/lib/jvm/openjdk-10.0.2-internal/lib/tzdb.dat
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/appletviewer.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/idlj.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jar.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jarsigner.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/java.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/javac.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/javadoc.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/javap.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jcmd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jconsole.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jdb.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jdeps.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jinfo.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jjs.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jmap.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jps.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jrunscript.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jstack.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jstat.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/jstatd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/keytool.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/orbd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/pack200.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/rmic.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/rmid.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/rmiregistry.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/schemagen.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/serialver.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/servertool.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/tnameserv.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/unpack200.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/wsgen.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/wsimport.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/ja_JP.UTF-8/man1/xjc.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/appletviewer.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/idlj.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jar.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jarsigner.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/java.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/javac.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/javadoc.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/javap.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jcmd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jconsole.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jdb.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jdeps.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jinfo.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jjs.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jmap.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jps.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jrunscript.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jstack.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jstat.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/jstatd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/keytool.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/orbd.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/pack200.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/rmic.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/rmid.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/rmiregistry.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/schemagen.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/serialver.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/servertool.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/tnameserv.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/unpack200.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/wsgen.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/wsimport.1
/usr/lib/jvm/openjdk-10.0.2-internal/man/man1/xjc.1
/usr/lib/jvm/openjdk-10.0.2-internal/release

%files dev
%defattr(-,root,root,-)
/usr/lib/jvm/openjdk-10.0.2-internal/include/classfile_constants.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/jawt.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/jdwpTransport.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/jni.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/jvmti.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/jvmticmlr.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/linux/jawt_md.h
/usr/lib/jvm/openjdk-10.0.2-internal/include/linux/jni_md.h

%files lib
%defattr(-,root,root,-)
/usr/lib/jvm/openjdk-10.0.2-internal/lib/jli/libjli.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libattach.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt_headless.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libawt_xawt.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libdt_socket.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libextnet.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libfontmanager.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libinstrument.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2gss.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2pcsc.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libj2pkcs11.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjaas_unix.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjava.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjavajpeg.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjawt.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjdwp.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjimage.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsig.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsound.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libjsoundalsa.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/liblcms.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement_agent.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmanagement_ext.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libmlib_image.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libnet.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libnio.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libprefs.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/librmi.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsaproc.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsctp.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsplashscreen.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libsunec.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libunpack.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libverify.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/libzip.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/server/libjsig.so
/usr/lib/jvm/openjdk-10.0.2-internal/lib/server/libjvm.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openjdk10/LICENSE
/usr/share/package-licenses/openjdk10/src_java.desktop_share_native_libsplashscreen_giflib_COPYING
/usr/share/package-licenses/openjdk10/src_java.desktop_share_native_libsplashscreen_libpng_LICENSE
/usr/share/package-licenses/openjdk10/src_java.smartcardio_unix_native_libj2pcsc_MUSCLE_COPYING
/usr/share/package-licenses/openjdk10/test_fmw_gtest_LICENSE
/usr/share/package-licenses/openjdk10/test_jdk_javax_xml_ws_xsanymixed_CopyingResponse.java
